DROP DATABASE IF EXISTS PROYECTO_CASINO;
CREATE DATABASE PROYECTO_CASINO;
USE PROYECTO_CASINO;

-- Tabla de usuario
CREATE TABLE USUARIO (
    DNI VARCHAR(9) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO1 VARCHAR(50) NOT NULL,
    APELLIDO2 VARCHAR(50),
    FECHA_NACIMIENTO DATE NOT NULL,
    USER_NAME VARCHAR(50) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    USER_PASSWORD VARCHAR(255) NOT NULL,
    NUMERO_TELEFONO VARCHAR(15) NOT NULL,
    CONSTRAINT PK_USUARIO PRIMARY KEY (DNI)
);

INSERT INTO USUARIO (DNI, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, USER_NAME, EMAIL, USER_PASSWORD, NUMERO_TELEFONO) VALUES 
('12345678A', 'Pedro', 'García', 'López', '1990-05-15', 'Pedro90', 'pedro.garcia@example.com', 'Password123!', '123456789'),
('87654321B', 'María', 'Fernández', 'Pérez', '1985-07-20', 'Maria85', 'maria.fernandez@example.com', 'SecurePass456!', '987654321');

SELECT * FROM USUARIO;